#!/usr/bin/env python3
"""
Definitive fix script for all_features_test.go.
Reads from backup, properly converts double-quoted Go strings to backtick,
fixing all escape sequences correctly.
"""
import re, sys

BACKUP = "/root/project/backend/handlers/all_features_test.go.bak"
OUTPUT = "/root/project/backend/handlers/all_features_test.go"

with open(BACKUP, "rb") as f:
    raw = f.read()

lines = raw.split(b"\n")
output_lines = []

for line_num, line in enumerate(lines, 1):
    # Match: optional whitespace + mock.ExpectQuery("SQL") or mock.ExpectExec("SQL") + optional trailing .
    # The pattern: mock.ExpectQuery("...")  or  mock.ExpectExec("...")
    # We need to capture: prefix (including opening paren), SQL between quotes, suffix
    
    m = re.match(rb'(\s*mock\.(ExpectQuery|ExpectExec)\()"(.*?)"(\)\.?\s*)$', line)
    if m:
        prefix = m.group(1)   # e.g. b'\tmock.ExpectQuery('
        sql_inside = m.group(3)  # SQL as it appears between double quotes in Go source
        suffix = m.group(4)   # e.g. b').' or b')'
        
        # Now we need to convert the Go double-quoted string to a backtick string.
        # The SQL inside the double quotes has Go escape sequences:
        #   \\ -> literal backslash
        #   \$ -> literal $ (but \$ is not a valid Go escape, so it appears as \$ in source)
        #   \* -> literal * (but \* is not a valid Go escape, so it appears as \* in source)  
        #   \( -> literal ( (but \( is not a valid Go escape)
        #   \) -> literal ) (but \) is not a valid Go escape)
        #
        # In the backup file bytes, the double-quoted string contains these byte sequences:
        # For a placeholder $1: the source has \$1 (backslash dollar 1) but since \$ is invalid,
        #   the file actually has \\$1 (backslash backslash dollar 1) which Go interprets as \$1 (literal backslash + $1)
        # Wait - no. Let me check what's ACTUALLY in the file bytes.
        
        # Actually, the issue is much simpler. The backup file was CREATED by writing Go source
        # that contains double-quoted strings. In those strings, the author wrote things like:
        #   "SELECT ... WHERE email = \$1"
        # But in Go source, \$ is not a valid escape. So the file on disk would have the literal
        # bytes: $ \ $ 1 inside the quotes. Go would then fail to compile with "unknown escape".
        #
        # BUT - the backup file DOES compile (mostly). The "unknown escape" error is on line 27.
        # So most lines actually have valid Go escapes. How?
        #
        # The answer: the file was likely generated by a script that properly escaped things.
        # In Go double-quoted strings:
        #   "\\$" in source = backslash + dollar in the actual string value
        #   The source bytes are: \ \ $  (two backslashes + dollar)
        #   Go interprets \\ as \, so the string value has: \ $  (one backslash + dollar)
        #
        # So for the SQL "SELECT ... WHERE email = \$1":
        #   Source bytes: ... = \ \ $ 1 "
        #   Go string value: ... = \ $ 1
        #   This is what gets sent to sqlmock as the regex pattern.
        #
        # For backtick conversion, we want the literal characters \, $, 1 in the backtick string.
        # In Go backtick source: `SELECT ... WHERE email = \$1`
        #   The source bytes are: \ $ 1  (one backslash + dollar + 1)
        #   Backtick strings are raw, so the string value is: \ $ 1
        #   As a regex: \$ matches literal $, 1 matches 1. Correct!
        #
        # So the transformation from double-quoted source to backtick source is:
        #   Remove one level of backslash escaping.
        #   \\ in source -> \ in backtick source
        #   \" in source -> " in backtick source (but quotes won't appear in SQL)
        
        sql_backtick = sql_inside
        
        # Process escape sequences: replace \\ with \ throughout
        # In the source bytes, \\ appears as two backslash bytes (0x5c 0x5c)
        # We want one backslash byte (0x5c) in the backtick version
        sql_backtick = sql_backtick.replace(b'\\\\', b'\\')
        
        # Also handle any other escape sequences that might be present
        # \" -> " (though unlikely in SQL)
        sql_backtick = sql_backtick.replace(b'\\"', b'"')
        # \n -> actual newline (unlikely in SQL but handle it)
        sql_backtick = sql_backtick.replace(b'\\n', b'\n')
        # \t -> actual tab
        sql_backtick = sql_backtick.replace(b'\\t', b'\t')
        # \r -> actual carriage return
        sql_backtick = sql_backtick.replace(b'\\r', b'\r')
        
        # Build the new line with backtick
        new_line = prefix + b'`' + sql_backtick + b'`' + suffix
        output_lines.append(new_line)
        continue
    
    output_lines.append(line)

result = b'\n'.join(output_lines)

# Write output
with open(OUTPUT, "wb") as f:
    f.write(result)

print(f"Wrote {len(result)} bytes to {OUTPUT}")

# Verify key lines
with open(OUTPUT, "rb") as f:
    check = f.read()

check_lines = check.split(b'\n')
for idx in [13, 26, 122, 137]:
    if idx < len(check_lines):
        line = check_lines[idx]
        print(f"\nLine {idx+1}: {line.decode('latin-1')[:120]}")
        # Show SQL portion between backticks
        bt_start = line.find(b'`')
        if bt_start >= 0:
            bt_end = line.find(b'`', bt_start + 1)
            if bt_end >= 0:
                sql = line[bt_start+1:bt_end]
                print(f"  SQL ({len(sql)} bytes): {sql[:100]}")
                print(f"  Hex: {sql[:50].hex()}")
                # Show byte-by-byte for first COUNT occurrence
                if b'COUNT' in sql:
                    c_idx = sql.find(b'COUNT')
                    snippet = sql[c_idx:c_idx+15]
                    print(f"  COUNT hex: {snippet.hex()}")
                    for i, b in enumerate(snippet):
                        ch = chr(b) if 32 <= b < 127 else '?'
                        print(f"    [{i}] 0x{b:02x} ({ch})")
                # Show $ context
                if b'$' in sql:
                    d_idx = sql.find(b'$')
                    ctx = sql[max(0,d_idx-3):d_idx+3]
                    print(f"  $ context hex: {ctx.hex()}")
                    for i, b in enumerate(ctx):
                        ch = chr(b) if 32 <= b < 127 else '?'
                        print(f"    [{i}] 0x{b:02x} ({ch})")

# Count backtick vs double-quoted
bt_count = check.count(b'mock.ExpectQuery(`') + check.count(b'mock.ExpectExec(`')
dq_count = check.count(b'mock.ExpectQuery("') + check.count(b'mock.ExpectExec("')
print(f"\nStats: {bt_count} backtick mocks, {dq_count} double-quoted mocks")
