apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-staging
  namespace: staging
spec:
  ingressClassName: nginx
  rules:
  - host: server-ad5ae8ea-5132-4cd3-b11f-5cb0f43bdc53.eu-west1-a.arvancompute.ir
    http:
      paths:
      # === Identity Service ===
      - path: /api/v1/register
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/login
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/logout
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/me
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/referrals
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/commissions
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      - path: /api/v1/referrals/earnings
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 8081
      # === Product Service ===
      - path: /api/v1/products
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 8082
      - path: /api/v1/categories
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 8082
      - path: /api/v1/bundles
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 8082
      - path: /api/v1/recommendations
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 8082
      - path: /api/v1/product-requests
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 8087
      # === Commerce Service ===
      - path: /api/v1/guest-orders
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/coupons
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/orders
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/cart
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/wishlist
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/recently-viewed
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      - path: /api/v1/compare
        pathType: Prefix
        backend:
          service:
            name: commerce-service
            port:
              number: 8083
      # === Community Service ===
      - path: /api/v1/posts
        pathType: Prefix
        backend:
          service:
            name: community-service
            port:
              number: 8084
      - path: /api/v1/community
        pathType: Prefix
        backend:
          service:
            name: community-service
            port:
              number: 8084
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: community-service
            port:
              number: 8084
      - path: /api/v1/profile
        pathType: Prefix
        backend:
          service:
            name: community-service
            port:
              number: 8084
      # === Review Service ===
      - path: /api/v1/reviews
        pathType: Prefix
        backend:
          service:
            name: review-service
            port:
              number: 8085
      # === Payment Service ===
      - path: /api/v1/exchange-rates
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 8086
      - path: /api/v1/payments
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 8086
      - path: /api/v1/settings
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 8086
      # === Admin Service ===
      - path: /api/v1/admin
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 8087
      # === Media Service ===
      - path: /api/v1/media
        pathType: Prefix
        backend:
          service:
            name: media-service
            port:
              number: 8088
