apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: {{INGRESS_HTTP_NODEPORT}}
    protocol: TCP
    name: http
  - port: 443
    targetPort: https
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: ingress-nginx-controller
