apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  allow-underscores-in-headers: "true"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  proxy-real-ip-cidr: "0.0.0.0/0"
  ssl-redirect: "false"
  use-geoip: "false"
  use-geoip2: "false"
  use-brotli: "false"
  enable-modsecurity: "false"
  enable-opentracing: "false"
  http-snippet: |
    client_max_body_size 50m;
