apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: nginx-api-gateway
