apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8083
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8084
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8086
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8087
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: production
spec:
  selector:
    app: backend-pod
  ports:
  - name: http
    port: 80
    targetPort: 8088
    protocol: TCP
