-- Add missing columns to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS digital_formats TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_pwyw BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pwyw_min_price DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pinned_at TIMESTAMP WITH TIME ZONE;

-- Add missing columns to categories table
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_url TEXT DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

-- Add missing columns to product_images table
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS image_type VARCHAR(50) DEFAULT 'full';
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS width INTEGER DEFAULT 0;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS height INTEGER DEFAULT 0;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS file_size_bytes BIGINT DEFAULT 0;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS storage_path TEXT DEFAULT '';
