ALTER TABLE order_items ADD COLUMN IF NOT EXISTS download_count INTEGER DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_title TEXT DEFAULT '';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_slug TEXT DEFAULT '';
